name: Deploy Hexo Blog

on:
  push:
    branches:
      - main # 如果你的源码分支名是 master，请改为 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 如果你的主题是作为 git submodule 引入的，这一行非常重要

      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 推荐使用较新的 LTS 版本
          cache: 'npm'

      # 3. 安装依赖
      - name: Install Dependencies
        run: npm install

      # 4. 生成静态文件
      - name: Build Hexo
        run: npx hexo generate

      # 5. 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 系统自动生成，无需手动配置
          publish_dir: ./public        # Hexo 生成的静态文件所在目录
          publish_branch: gh-pages      # 静态文件存放的分支名
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'         # 使用 Hexo 部署博客